baseURL = 'https://blog-lap-trinh-mang.vercel.app/'
languageCode = 'vi'
title = 'HiuLab'
theme = 'pehtheme-hugo'
summaryLength = '20'
googleAnalytics = ''
disqusShortname = '' 

[params]
  description = 'Blog chia sẻ kiến thức về lập trình Java và JavaScript'
  mainSections = ['blog']  # ← QUAN TRỌNG: Thay 'posts' thành 'blog' vì bạn dùng folder blog/

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  
[params.author]
  name = 'Tiết Thanh Minh Hiếu'
  bio = 'Từ một sinh viên CNTT, tôi đã tìm thấy niềm đam mê thực sự tại giao điểm giữa AI và Cybersecurity.'
  avatar = 'images/avatar_2.png' # Tạo ảnh avatar sau
  twitter = '' # Để trống nếu không có

[pagination]
  pagerSize = 9 # Hiển thị 9 bài/trang (bạn có 9 bài)

[menu]
  [[menu.main]]
    name = 'Trang chủ'
    pageRef = '/'
    weight = 10

  [[menu.main]]
    name = 'Bài viết'
    pageRef = '/blog'
    weight = 15
  
   [[menu.main]]
    name = 'Danh mục'
    pageRef = '/categories'
    weight = 20

  [[menu.main]]
    name = 'Thẻ'
    pageRef = '/tags'
    weight = 25
  
  [[menu.main]]
    name = 'Về tôi'
    pageRef = '/about'
    weight = 30
  
  [[menu.main]]
    name = 'Liên hệ'
    pageRef = '/contact'
    weight = 35 
  
  

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


  
  